### ISSUE TITLE
[Request] - Add Air quality information

### ISSUE THREAD

**Issue by postadelmaga** [jackd248/temps#10]
Nowadays the air quality is more and more a concern in many cities and in the same way as if it is going to rain I will bring with me an umbrella, if the air is very bad today I will bring with me a mask ...

I feel like adding such information to the gui will be useful at least for 2 reason:
 - help people to have a easy access to the Air Quality information 
 - stimulate the sensibility to the pollution problem

This is an example of some related API, Real-time Air Quality Tile API:
http://aqicn.org/faq/2015-09-18/map-web-service-real-time-air-quality-tile-api/

Thanks for your effort in making this nice project

**Comment by konradmichalik** [comment]
This is at least not a bad idea, especially for regions with massive air quality problems. But for now I will leave temps as simple as possible, including the displayed information. I will have so much more information provided by the weather api (like wind speed, humidity or pressure). Maybe later I know how to combine all of this information with the minimalistic design.

But cheers for the participation!
