### ISSUE TITLE
Temps won't start

### ISSUE THREAD

**Issue by CorentinDy** [jackd248/temps#11]
Hi,
i just download Temps for Windows 10 (tried x64 and x86 version).
But no luck it won't start.

If you need some informations i'm here , just don't have a thing to show for now .

Is there any requirements needed ? or something i've forget ?

**Comment by konradmichalik** [comment]
Hey there,

mh, do you noticed that temps is a tray/menubar app? So when you start the app, you will find the temps icon beneath the other user and system apps. After you clicking the icon or using the shortcut <cmd>STRG</cmd> + <cmd>Shift</cmd> + <cmd>W</cmd> the app will start. 

Hope this will help.

**Comment by CorentinDy** [comment]
My bad i was about to write that it takes about 20min to start , on my home pc it takes about 3sec to start but they have the same configuration and installation maybe it something on my side .

Great app btw !

**Comment by konradmichalik** [comment]
Cheers ;)

**Comment by CorentinDy** [comment]
Is there any way to help to translate in french ?

**Comment by konradmichalik** [comment]
For now there is no translation planned. But this could be a nice feature. I will let you know when I need your help with the translation :)
