### ISSUE TITLE
Usage of the term "lightweight"

### ISSUE THREAD

**Issue by jobukkit** [jackd248/temps#12]
A weather forecasting application that includes a whole HTML5 engine, putting the download size at 41,7 MB, can't be considered lightweight in any way.

**Comment by konradmichalik** [comment]
You're right. When I was creating the landing page I considered about the look and the design. "Lightweight" was more meant for the style then the functional application. I know about the inefficiency using the whole electron environment for a simple weather application. But this is more a huge practise project for me then a marketing idea or so.  

So if you like it, i'm happy, if you want to contribute you're welcome.
