### ISSUE TITLE
Won't start on Ubuntu Xenial - prints "undefined" in console

### ISSUE THREAD

**Issue by kjpuchala** [jackd248/temps#13]
Trying to run from downloads:
>Temps-linux-x64$ ./Temps 
undefined
{ Error: connect ETIMEDOUT 151.101.84.133:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '151.101.84.133',
  port: 443,
  response: undefined }

**Comment by konradmichalik** [comment]
Still got this problem? I am a little helpless with that.

**Comment by konradmichalik** [comment]
Closed because of no response.
