### ISSUE TITLE
Temps window not showing up in Windows 7 64bit

### ISSUE THREAD

**Issue by sidharthcnadhan** [jackd248/temps#18]
Hi,

Temps window is not showing up in Windows 7 64bit.
The icon is showing up in the system tray and changing according to the weather of the default location 
(Berlin).
But left click or right click on the icon has no response. Not able to change the location or any other settings.
Please look into this issue.

thanks,
Sidharth.

**Comment by konradmichalik** [comment]
You can get to the settings by clicking the two lines in the upper left. 
![screenshot](https://cloud.githubusercontent.com/assets/4558190/20277717/09434566-aaa2-11e6-8caf-f50c1d89d7fd.jpg)

Or you click on the current location or using shortcut "STRG" + "S" while temps is open. Hope this will help.

**Comment by sidharthcnadhan** [comment]
Hi Konrad Michalik,

Thanks for the response.
But the problem is that, the Temps window itself is not opening.
All I have is the small system tray icon, on which left/right click has no response.
It just changes the icon according to the weather in Berlin,DE.

thanks,
Sidharth.

**Comment by sidharthcnadhan** [comment]
Hi,

This issue got resolved in the latest update.
Thanks a lot. Closing the bug.

Regards,
Sidharth.
