### ISSUE TITLE
Negative temperature value doesn't fit into label

### ISSUE THREAD

**Issue by thevasya** [jackd248/temps#19]
When it's -10°C and below (i.e. two digits), there is an extra line break. See the screenshot:

![image](https://cloud.githubusercontent.com/assets/1012519/20271812/9a71a2e6-aabe-11e6-9275-23cc5c7ae581.png)

When it's warmer, it looks fine. I'm on Ubuntu 14.04, if this has any effect.

Thanks!

**Comment by konradmichalik** [comment]
You're absolutly right. It was never so cold, that I was testing this case. I'll fix this in the next version. Cheers!

**Comment by konradmichalik** [comment]
Solved by version v0.7.0

**Comment by thevasya** [comment]
Thank you! Looks perfect now.
