### ISSUE TITLE
I cannot uninstall package

### ISSUE THREAD

**Issue by c0d3sling3r** [jackd248/temps#20]
I have installed the package, But I think it's a broken one. Now I want to uninstall that, But when I hit this command `sudo npm unistall -g temps`, I see no verbos report and it's clear that the package is not uninstalled. Because next time I'd login it will automatically run.

What should I do?? HELP!!

**Comment by konradmichalik** [comment]
I never tried to install them via npm for now. Normally you can remove all of the downloaded files and the app is gone.

**Comment by c0d3sling3r** [comment]
The crazy problem is here: I cannot find the installed directory. :-|

**Comment by mkg20001** [comment]
On Linux it might be: `/usr/lib/node_modules/temps`

**Comment by konradmichalik** [comment]
Did you find the installed directory? @mojsho

**Comment by konradmichalik** [comment]
Closed because of no response.
