### ISSUE TITLE
Failure during data fetching

### ISSUE THREAD

**Issue by iCHAIT** [jackd248/temps#3]
I am not able to use the application. It indefinitely flashes `Failure during data fetching` and also the time shown is wrong, as far as my location is concerned (It shows 18:50 whereas its 22:20 in my area). Am I missing something?

Here is a screenshot for reference -

![screen shot 2016-09-25 at 10 20 09 pm](https://cloud.githubusercontent.com/assets/8472314/18816810/6b450d4a-836e-11e6-935b-e573e64ed4a0.png)

**Comment by iCHAIT** [comment]
I tried getting an API key for my location as well, but the third party service that you are using seems to be unresponsive on my end :/

**Comment by konradmichalik** [comment]
You need a free API key from [openweathermap](http://openweathermap.org/). To get one, you need to sign up, so you can fetch weather information. Then you can get weather data for almost every place in the world.
Unfortunately the app is using a free weather information service. So sometimes the data seems to unobtainable or the city can't be found anymore. These are almost temporary problems. 
If you still have problems with your API key, I can give you one of mine for testing purpose.

**Comment by Bicet** [comment]
`I tried getting an API key for my location as well, but the third party service that you are using seems to be unresponsive on my end :/`

Same problem here, I've registered an api key and select as city London, UK

**Comment by konradmichalik** [comment]
So where are you from? Did you try some other places? 
You got your own API key as well? You can also try to reload the application if there is a temporary error.

**Comment by Bicet** [comment]
Thank you for your reply @jackd248 :)
So I'm from Venice, Italy; in any case I've tried with different cities, and also the random one.
if you want I can share here my api keys, maybe the problem is on it :/

**Comment by konradmichalik** [comment]
You can send me your api key within an email if you want to keep them secret. 
I’m sorry about the troubles with the weather api, I will have a look for maybe a better option. 

-- 
Konrad Michalik
konradmichalik.eu 

Am 26. September 2016 um 18:50:32, Bicet (notifications@github.com) schrieb:

Thank you for your reply @jackd248 :)
So I'm from Venice, Italy; in any case I've tried with different cities, and also the random one.
if you want I can share here my api keys, maybe the problem is on it :/

**Comment by Bicet** [comment]
Again! Thank you for you fast reply :)

Here's the api key, you don't have to worry, about the problem, but I really like to try out this app :)

ababe97d31598236c4944045a39cafe9

**Comment by konradmichalik** [comment]
I’ve tried your key and there are no troubles at all. I’m not sure if there are some geographical restrictions with the open source service, I've never heard about other users having this problem. 

You can try out one of my keys as well, but I think that won't solve the problem. 
547bbdc38bd641bef6645cd2c4bc613f

**Comment by Bicet** [comment]
I don't know why, but as soon as I put your key it worked.
Changed back to my key and it worked!
Thank you :)

**Comment by konradmichalik** [comment]
Oh okay, I really have no idea how this happen, but sometimes you only need to give them a second try. Cheers 😄

**Comment by evertiro** [comment]
Just in case anyone else runs into the same issue, there's a lag on activation of OWS API keys. In my experience it takes between five and fifteen minutes for API keys to start working after they are created.
