### ISSUE TITLE
In 'Guangzhou, CN' city, the time in the upper right corner is wrong.

### ISSUE THREAD

**Issue by hejianxian** [jackd248/temps#6]
Hi!

This is a great project.  I ❤️ this.

So.

When I use this app, I found the time is wrong. My address is `Guangzhou, CN`, the current time is 09:57, but the time in the upper right corner is 10:57. More than an hour.

![image](https://cloud.githubusercontent.com/assets/6087438/19209477/a5660460-8d3d-11e6-8f00-c692f604fc73.png)

**Comment by konradmichalik** [comment]
Hey @Alex-fun,

Thanks for the compliment and nice to see where _temps_ is in use. ;)

You're right, _temps_ has a timezone bug. I fixed this issue by solving some offset and summertime problems. Thanks for your participation 👍 

The solution will be available soon in **v0.6.1**
